### ISSUE TITLE
Can you help me to add some pre-added event in Tacere.

### ISSUE THREAD

**Issue by lovebdsobuj** [ciasaboark/Tacere#50]
I want to add some pre-added (built-in) event in Tacere Database.
Just like Holiday Event Information App.

1. 
```
New Year
Jun 01, 2016
All Day
```
2. 
```
National Freedom Day
Feb 01, 2016
All Day
```

Can you create me a `class` for me including those holiday information.

I have small amount donation for this.

**Comment by ciasaboark** [comment]
Tacere does not maintain a separate record of calendar events.  It syncs from the system calendar.

The easiest way to get this information into the app would be to enable a holiday calendar.  If you are using google calendar there might be a national holiday calendar available (there is one for the US).

Once the calendar is enabled you can go to settings->select calendars and configure the default settings for that calendar.
