### ISSUE TITLE
Warn before closing tacere

### ISSUE THREAD

**Issue by guest4711** [ciasaboark/Tacere#64]
I use tacere for it's main purpose, to automatically silence my phone during events.
From time to time it happens events be disturbed by calls. Every time there was no  notification from tacere. So I think tacere was closed by accident swiping away some notifications...

So it would be fine if tacere would (optionally) ask whether closing the app is wanted. (E. g. afwall+  does it this way:  AFWall+ (Control network traffic) - https://f-droid.org/app/dev.ukanth.ufirewall

**Comment by ciasaboark** [comment]
Closing the notification _shouldn't_ cause any issues, but I'll need to test that to be sure.  Tacere makes heavy use of the Android AlarmManager to schedule wakes when an event begins or ends.  The service does not run continuously in the background.

Are you sure the notification was not closed by clicking the `ignore` option? 
If you close the notification by clicking the ignore button then the ringer state will be restored.

If you can provide a test case (event x begins at time t1 changes ringer state to y, call is received  at time t2) I will re-open this bug.

**Comment by guest4711** [comment]
@ciasaboark yes i'm shure i did not use the ignore button. When restarting tacere the phone has been silenced as expected...

I'll try to simulate it.
